### ISSUE TITLE
Tag the editorconfig spec versions in the editorconfig-core-test repository

### ISSUE THREAD

**Issue by ppalaga** [editorconfig/editorconfig-core-test#14]
Given that the tests in editorconfig-core-test git repository are the only formalish specification of the EditorConfig format, it would be handy to see which test set belongs to which version of the EditorConfig spec.

E.g. the current version of the spec is `0.12.0-final` and there should definitely exist `0.12.0-final` tag in the editorconfig-core-test repo, so that implementors can see clearly if they comply or not.

**Comment by xuhdev** [comment]
Let me clarify one thing: these are the tests for the core library. However, many work are supposed to be done in editor plugins. That means, these tests are not formal specification of the format. But yes, we should have tags, which I totally agree with you.

**Comment by xuhdev** [comment]
I've pushed a tag. Thank you.

**Comment by ppalaga** [comment]
Thanks @xuhdev !
