### ISSUE TITLE
Reuse of test code

### ISSUE THREAD

**Issue by rakus** [editorconfig/editorconfig-core-test#25]
I have setup my [own editorconfig plugin](https://github.com/rakus/vimscript-editorconfig) for Vim. For testing I took the `CMakeList.txt` from this project and translated them to vimscript. 

My project is released under the the [Vim License](https://github.com/vim/vim/blob/master/runtime/doc/uganda.txt).

At the beginning of the test files I added the following comment:
```
" This code is based on test code from the editorconfig-core-test project
" which is Copyright (c) 2011-2018 EditorConfig Team
" See https://github.com/editorconfig/editorconfig-core-test/blob/master/LICENSE.txt
```
Real example [here](https://github.com/rakus/vimscript-editorconfig/blob/cc312784042f05e6e352e503b8d83d75642ef885/tests/testset-editorconfig-core-glob.vim#L8-L10)

Is this comment sufficient, or do you want me to add something?
Maybe other requirements?

**Comment by xuhdev** [comment]
I think you also need to include the license text in your source tree (it's stated in the text of the license). In this case, normally what I do is to have your copyright notice above the one of the derived work. For example,

> Copyright (c) 2019 me
> Changes made since Mar 2019 are licensed under the Vim license.
>
> Copyright (c) 2011-2018 EditorConfig Team
> [Standard BSD notice here]

**Comment by rakus** [comment]
I updated my [LICENSE](https://github.com/rakus/vimscript-editorconfig/blob/master/LICENSE). If this is OK, you can close this issue, else I will rework it.

**Comment by xuhdev** [comment]
Awesome!
