### ISSUE TITLE
Break this project into 2 pieces

### ISSUE THREAD

**Issue by jedmao** [editorconfig/editorconfig-core-test#31]
Related to https://github.com/editorconfig/specification/issues/11, I'd like to break this project into two pieces:
1. One that handles just the INI parsing (into a common AST data structure).
1. Everything else (i.e., EditorConfig rules, directories).

This repo can continue to be used as it is today, but it would need to reference at least the first one above as a subproject.

**Comment by cxw42** [comment]
I have spent _way_ too much quality time with ctest and cmake recently :/ .  I respectfully disagree with this suggestion.  The test infrastructure is quite brittle, and I think a change of this magnitude would carry costs much greater than the benefits.

I would certainly support a separate test suite for the AST, if it were added to the specification.  Then a core could have two peer submodules: one for these tests and one for AST tests.  Alternatively, we could add the AST tests here, and condition them on an environment variable.

(I have already begun thinking about possible ways of replacing ctest to give us more flexibility, but don't have a detailed proposal yet.)

**Comment by cxw42** [comment]
@jedmao Can this be closed for now as well?  We can always reopen later if desired.

**Comment by jedmao** [comment]
I also haven't had the greatest experience with ctest and cmake. Have you run into any alternatives that are worth mentioning?

**Comment by cxw42** [comment]
Not existing, but I think I can roll my own ctest alternative fairly easily for the core's testing needs.  I'll let you know when I have a prototype :) .
