### ISSUE TITLE
Incorrect test?

### ISSUE THREAD

**Issue by dail8859** [editorconfig/editorconfig-core-test#37]
Been fighting with these two tests. 

https://github.com/editorconfig/editorconfig-core-test/blob/6c8fe6815b12f96f4b357d610ee1cd8da074880a/filetree/CMakeLists.txt#L70-L74

They test these two conditions...

https://github.com/editorconfig/editorconfig-core-test/blob/6c8fe6815b12f96f4b357d610ee1cd8da074880a/filetree/path_separator.in#L5-L9

At this point I'm assuming the first test is incorrect...or else I am completely not understanding how to implement them. 

---

My assumption is that `path/separator` would match any of the following (especially since the comment for the first test says `"Tests path separator match below top of path"`:
- `<root_dir>/path/separator`
- `<root_dir>/a/path/separator`
- `<root_dir>/b/c/path/separator`
- `<root_dir>/nested/path/separator`

However the test is expecting it to **not** have `key1=value1`

---

My other assumption is that `/top/of/path` would **only** match:
- `<root_dir>/top/of/path`

And not match any others such as:
- `<root_dir>/a/top/of/path`
- `<root_dir>/b/c/top/of/path`

Which seems to be correct according to the test.

**Comment by xuhdev** [comment]
The first test passed in `nested/path/separator` and it should not match `<root_dir>/path/separator`. I don't see any issue with it. Am I missing something?

**Comment by dail8859** [comment]
I'm still a bit confused...could you describe the difference between these two in simple English? I will take a guess to give you an idea what I am looking for...these are apparently wrong so any clarification is appreciated.

- `path/separator` - matches any file called `separator` that is any folder called `path`
- `/top/of/path` - matches the exact path `/top/of/path` under the current working directory

**Comment by xuhdev** [comment]
The first one says `nested/path/separator` should not match `path/separator`, and the second one says `top/of/path` should match `/top/of/path`

**Comment by dail8859** [comment]
So does a pattern starting with / have any special meaning?

**Comment by xuhdev** [comment]
It means the same path as the `.editorconfig`, because we said on editorconfig.org that it's meant to be the same as [gitignore](https://git-scm.com/docs/gitignore#_pattern_format). I believed that we probably have probably missed it in the spec.

**Comment by dail8859** [comment]
> It means the same path as the .editorconfig, because we said on editorconfig.org that it's meant to be the same as gitignore. I believed that we probably have probably missed it in the spec.

The specification and the main webpage state the EditorConfig glob patters are "_similar_ to the format accepted by gitignore" so I've never been sure which parts are similar and which parts are not (plus that link doesn't document anything about how braces are handled in various conditions, etc). 

I think I have enough of a grasp of it for now I hope

Thank you for all the time and explanation 👍
