### ISSUE TITLE
please provide a LICENSE or COPYING file

### ISSUE THREAD

**Issue by thkoch2001** [editorconfig/editorconfig-core-test#7]
The cmake files contain a BSD file but the *.in files do not.

The emacs editorconfig plugin uses this test files and I would like to include them in the Debian packaging. Thus I need to know unambiguously the licenses and copyright holders of all files.

Thank you!

(I also hate dealing with license stuff...)

**Comment by xuhdev** [comment]
@treyhunner According to the number of lines of modification, I think both of us should add an agreed license file, which we have missed before. Can you send a message to the mailing list to clarify the license? I'll send a similar message once you've sent.


> Copyright (c) 2011-2016 EditorConfig Team
> All rights reserved.
> 
> Redistribution and use in source and binary forms, with or without
> modification, are permitted provided that the following conditions are met:
> 
> 1. Redistributions of source code must retain the above copyright notice,
>    this list of conditions and the following disclaimer.
> 2. Redistributions in binary form must reproduce the above copyright notice,
>    this list of conditions and the following disclaimer in the documentation
>    and/or other materials provided with the distribution.
> 
> THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
> AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
> IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
> ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
> LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
> CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
> SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
> INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
> CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
> ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
> POSSIBILITY OF SUCH DAMAGE.
>

**Comment by xuhdev** [comment]
@treyhunner Can you send the message please? Then @thkoch2001 can continue with the Debian packaging. Thanks!

**Comment by treyhunner** [comment]
Yes I agree to license my work under Simplified BSD in this repo.

It looks like @josh and @linquize are the only other individuals who contributed to this project. As long as they are both also on-board with Simplified BSD, we should be fine to add that.

**Comment by josh** [comment]
👍

**Comment by xuhdev** [comment]
I also agree to license my work under Simplified BSD license in this repository. @linquize did not add significantly amount of lines in his commit so it should be fine for me to push the license file.
